[package]
name = "rust-leptos-2025-08-22"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "0.1"
console_log = { version = "1", features = ["color"] }
leptos = { version = "0.8", features = ["csr"] }
log = "0.4"
